import { IMeta } from 'src/app/shared/types/meta.inteface'

export const testMeta: IMeta = {
    i: "test_page",
    lbl: "Тестовая страница",
    modal: "n",
    rows: [
        {
            i: "a",
            vis: "y",
            fold: "n",
            lbl: "",
            modal: "n",
            gs: [
                {
                    i: "a",
                    lbl: "",
                    col: "12",
                    flex: "n",
                    typ: "t",
                    ci: "6",
                    ro: "n",
                    items: [
                        {
                            i: "num",
                            lbl: "№",
                            tag: "input",
                            typ: "text",
                            vis: "y",
                            req: "y",
                            ro: "n",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "id",
                            lbl: "ID",
                            tag: "input",
                            typ: "text",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "date",
                            lbl: "Дата",
                            tag: "input",
                            typ: "date",
                            vis: "y",
                            req: "y",
                            ro: "n",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "time",
                            lbl: "Время",
                            tag: "input",
                            typ: "time",
                            vis: "y",
                            req: "y",
                            ro: "n",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "sum",
                            lbl: "Сумма",
                            tag: "input",
                            typ: "number",
                            vis: "y",
                            req: "y",
                            ro: "n",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "bin",
                            lbl: "БИН",
                            tag: "input",
                            typ: "text",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "",
                            prop: "",
                        },
                        {
                            i: "author",
                            lbl: "Автор",
                            tag: "input",
                            typ: "text",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "",
                            prop: "",
                        }
                    ],
                }
            ]
        },
        {
            i: "a",
            vis: "y",
            fold: "n",
            lbl: "",
            modal: "n",
            gs: [
                {
                    i: "a",
                    lbl: "",
                    col: "6",
                    flex: "n",
                    typ: "f",
                    ci: "6",
                    ro: "n",
                    items: [
                        {
                            i: "update",
                            lbl: "Обновить",
                            tag: "button",
                            typ: "",
                            vis: "y",
                            req: "n",
                            ro: "n",
                            par: "",
                            evt: "update-table",
                            prop: "",
                        },
                        {
                            i: "download",
                            lbl: "Загрузить",
                            tag: "button",
                            typ: "text",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "download-table",
                            prop: "",
                        },
                        {
                            i: "choose",
                            lbl: "Выберите",
                            tag: "select",
                            typ: "",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "",
                            prop: "",
                            list: ['Первый вариант', 'Второй вариант', 'Третий вариант']
                        },
                    ],
                },
                {
                    i: "a",
                    lbl: "",
                    col: "6",
                    flex: "n",
                    typ: "f",
                    ci: "6",
                    ro: "n",
                    items: [
                        {
                            i: "search",
                            lbl: "Поиск",
                            tag: "input",
                            typ: "",
                            vis: "y",
                            req: "n",
                            ro: "n",
                            par: "",
                            evt: "search-table",
                            prop: "",
                        },
                        {
                            i: "edit",
                            lbl: "Редактировать",
                            tag: "button",
                            typ: "",
                            vis: "y",
                            req: "n",
                            ro: "n",
                            par: "",
                            evt: "edit-table",
                            prop: "",
                        },
                        {
                            i: "delete",
                            lbl: "Удалить",
                            tag: "button",
                            typ: "text",
                            vis: "y",
                            req: "n",
                            ro: "y",
                            par: "",
                            evt: "delete-table",
                            prop: "",
                        },
                    ],
                }
            ]
        }
    ],
    actions: [
        {
            evt: "form-actions",
            dis: "n",
            vis: "y",
            lbl: "Действия",
            alt: "Действия",
            icon: "action1",
            id: "option-actions",
        },
        {
            evt: "form-print",
            dis: "n",
            vis: "y",
            lbl: "Печать",
            alt: "Печать",
            icon: "print2",
            id: "",
        }
    ]
}